### PR TITLE
Allow hiding when focus is lost

### PR DESCRIPTION
**Pull request by andersmmg**
Adds an option to hide the window when focus is lost

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@andersmmg I was planning to add an option to toggle "Always on top". What do you think?

**Comment by andersmmg** [comment]
Would it go behind the newly selected window then, or hide similar to how it does with this option?

**Comment by Melvin-Abraham** [comment]
It will definitely not close the window but again will not keep the window pinned to the top. So, if you want to include this option to close the window when blur, let's make it a dropdown option for **Window Behavior** (under _WINDOW_) with options: "Normal" (please recommend a better name), "Always on top", "Close on blur".

**Comment by andersmmg** [comment]
Yeah, that sounds perfect! I can't think of any better name than just "Normal", but I do thing using "Hide On Blur" is better than "Close On Blur," since it's not closing the assistant, just hiding the window. Both work though, really

**Comment by Melvin-Abraham** [comment]
Sure, "Hide on blur" also seems great

**Comment by Melvin-Abraham** [comment]
Closing this PR in favor of df20e6fae

**Pull request closed without merging**
