### PR TITLE
Update project guidelines

### PR DESCRIPTION
**Pull request by esau-morais**
### Upcoming changes

* `CONTRIBUTING.md` file: Help contributors
* `CODE_OF_CONDUCT.md` file: Define rules
* `issue-action.yml` file: Auto label issues and PRs
* `.editorconfig` file: Define a default editor linting

**Note:** To enable the GitHub Actions, it's necessary to [create an encrypted secret](https://docs.github.com/en/actions/reference/encrypted-secrets). Also, the name `GITHUB_TOKEN` will need to be changed, once the name probably will be considered as invalid.

### Context

Related to issue #177

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@esau-morais I think indent size of 2 would look less spread out than an indent size of 4. What do you think?

**Comment by esau-morais** [comment]
> @esau-morais I think indent size of 2 would look less spread out than an indent size of 4. What do you think?

Indeed. Going to change it now and also check some things in the Issue Action

**Comment by esau-morais** [comment]
Just got to test the Issue Action and it seems to work very well, although I still working on the keywords to identify better the issues.

Issue action working

### Steps to reproduce

Before creating a new token, go to your profile settings and, in the "Developer Settings" option, go to "Personal Access Tokens". Then, generate a new token called `GAUDC` and copy it.

1. Go to the Google-Assistant-Unofficial-Desktop-Client Settings
2. You'll be able to see in the sidebar (at the left) an option called `Secrets`
3. Name it `GAUDC_TOKEN` and paste that first token that you have copied. **Note:** _If you forgot, go to that same page and regenerate it._

**Comment by Melvin-Abraham** [comment]
@esau-morais I have added a token with name `GAUDC_TOKEN`. I'll review the PR and make changes if required...

**Comment by Melvin-Abraham** [comment]
@esau-morais As per the AirBnb JS standard (specified in `CONTRIBUTING.md`), we must use single quotes for enclosing strings. The changes in this PR contain strings with double quotes instead. Would you mind to look at it? :)

**Comment by esau-morais** [comment]
> Would you mind to take a look at it?

Sure! I totally forgot that part 😅

> Maybe we can add this to prettier configuration file

I never used the `.editorconfig`, actually LOL. So, I'm gonna change it too.

**Comment by Melvin-Abraham** [comment]
I think `.prettierrc` file itself will take care of the formatting for the workspace so the user only need to add the following in their `settings.json` **mandatorily** if they have prettier installed:

```json
"editor.defaultFormatter": "esbenp.prettier-vscode"
```

This will make sure that prettier rules are enforced when the user decides to format or the file automatically formats on save.

**Comment by esau-morais** [comment]
Thank you! Also, just got to see your changes and successfully applied here. In this case, the `.editorconfig` file still necessary?

**Comment by Melvin-Abraham** [comment]
> In this case, the `.editorconfig` file still necessary?

Yeah. We can keep it there... :)

_Just a minor suggestion for the line:_

> Make sure you have this **line** in your `settings.json` file **to set the Prettier extension as default formatter** and apply the .prettierrc formatting file

Also, the dev must have Prettier installed, only then will this code styling will be enforced by it

**Comment by Melvin-Abraham** [comment]
@esau-morais I'll make some minor changes and merge it...

**Comment by Melvin-Abraham** [comment]
@esau-morais Is there anything else you want to add to this PR?

**Comment by esau-morais** [comment]
> @esau-morais Is there anything else you want to add to this PR?

One of my suggestions was to add the new GitHub Discussions and engage with the community, but I don't know if that's actually necessary.

**Comment by Melvin-Abraham** [comment]
> > @esau-morais Is there anything else you want to add to this PR?
> 
> One of my suggestions was to add the new GitHub Discussions and engage with the community, but I don't know if that's actually necessary.

I have enabled Discussions for this repo. Anything else this PR needs?

**Comment by esau-morais** [comment]
I think that's it for this PR. Thank you for all the time! 😊

**Comment by Melvin-Abraham** [comment]
Great! I'll merge this PR then...

**Comment by esau-morais** [comment]
> Great! I'll merge this PR then...

I think there's a silly problem that I just got to see 🤦‍♂️. If the user goes to the `CONTRIBUTING.md` file and click the link that redirects to create a new issue/feature request, it starts with a blank issue, which doesn't make sense at all, once there's a file that set the issue to start with the specified content.

**Pull request merged**
