### PR TITLE
feat: Change hover color to red for `close-btn`

### PR DESCRIPTION
**Pull request by sumeshir26**
Makes it similar to how Windows handles the close button.
Will make it more clear when you are closing instead of minimizing.

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@sumeshir26 It seems like there's some CSS syntax errors. Can you check that?

**Comment by sumeshir26** [comment]
@Melvin-Abraham Fixed!

**Comment by sumeshir26** [comment]
@Melvin-Abraham Are you still interested in this PR or should I close this?

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Seems like the current color scheme works fine. So, you may close this PR...

**Pull request closed without merging**
