### PR TITLE
fix: Fix Window Transparency on Linux

### LINKED ISSUE #357: Graphical bug
**Describe the bug**
image
On all the corners

**To Reproduce**
1. Download the latest commit (https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/tree/ff7e18b8ade920dfdf2094372829c7fef010cc8b)
2. Build
3. Open the app

**Expected behavior**
image

**Desktop (please complete the following information):**
 - OS: Pop_OS! 20.10
 - Version ff7e18b8ade920dfdf2094372829c7fef010cc8b

**Additional context**
The latest working commit that I've tested is 0b1bda1be4451b780cef4b97d1a3b91ffe0d4445. (On other commits without the graphical bug they're missing functionalities)

### PR DESCRIPTION
**Pull request by sumeshir26**
I found the solution [over here](https://github.com/ItsWendell/google-assistant-desktop-client/issues/8)
Resolves #357

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
Can you paste the Assistant info from **Settings** > **Developer Options** > **About Assistant**?

**Comment by sumeshir26** [comment]
@Melvin-Abraham Here it is:-

> Version: 1.0.0-rc.2
> Commit ID: 9b6bac7ab392c613bcb06b5cf1007db6de21555b
> Commit Date: Fri May 28 12:48:31 2021 -0500
> Electron: 10.3.2
> Chrome: 85.0.4183.121
> Node.js: 12.16.3
> V8: 8.5.210.26-electron.0
> OS: Linux x64 5.4.0-1033-gke

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Are you running it in a VM?

**Comment by sumeshir26** [comment]
@Melvin-Abraham Yeah. I run it in a VM because I don't want to mess something up while coding.

**Pull request closed without merging**
