### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by QuestYouCraft**
See #489 for more info

@Melvin-Abraham, merge this.

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@QuestYouCraft Did you test it on older versions of the specified OSes?

**Comment by im-coder-lg** [comment]
Well, I was the one who told him, but I clearly told that I am unsure on Mac OS and Linux. I am sure for Windows because I use GAUDC on my Windows 7 PC

**Comment by QuestYouCraft** [comment]
> I clearly told that I am unsure on Mac OS and Linux

So you said that

>  I know it would work on latest Linux distributions, but unsure about Mac OS

Or is it false?

_P.s. for the future: a word spoken is past recalling._

---

> @QuestYouCraft Did you test it on older versions of the specified OSes?

No, but @im-coder-lg testing GAUDC. I can say for sure that this works on Windows 7+. I don't have time to test it yet. As soon as there is time, I will do it.

---

In general, I want to help you and the rest of the people who will study this project, but I understand that you do not need any help from the GitHub community at all. Right?

**Comment by im-coder-lg** [comment]
woah wait what? I am clearly unsure. I think it works maybe on Linux distros from maybe 2018, but major requirement is NodeJS and NPM(latest maybe?) and for Windows 7, it works on v12+ but below v13

**Comment by im-coder-lg** [comment]
> Well, I was the one who told him, but I clearly told that I am unsure on Mac OS and Linux. I am sure for Windows because I use GAUDC on my Windows 7 PC

What I meant was that I think it works on latest distros but am still unsure. I am sure for Debian 10 and Ubuntu 20.04. Maybe Fedora 33+, Debian 9+, Ubuntu 19+(?). I tried on Gitpod running Ubuntu 20.04 and it failed at NPM but Gitpod runs on a server, it does fail.

**Comment by im-coder-lg** [comment]
Surely works on latest LTS of Ubuntu and Debian 10+(**NOTE**:**<kbd>WSL</kbd>**), sine Ubuntu is **based** on debian. I don't use Fedora or openSUSE, because I use apt mainly for installing

**Comment by im-coder-lg** [comment]
> > I clearly told that I am unsure on Mac OS and Linux
> 
> So you said that
> 
> > I know it would work on latest Linux distributions, but unsure about Mac OS
> 
> Or is it false?

I told that, and I was not clearly sure because I use Ubuntu 20.04, okay?

> 
> _P.s. for the future: a word spoken is past recalling._
> 

What was that?

> > @QuestYouCraft Did you test it on older versions of the specified OSes?
> 
> No, but @im-coder-lg testing GAUDC. I can say for sure that this works on Windows 7+. I don't have time to test it on all OS yet. As soon as there is time, I will do it.

Try using VMs if you use Mac OS.

> 
> In general, I want to help you and the rest of the people who will study this project, but I understand that you do not need any help from the GitHub community at all. Right?

Wait, what? An open-source project means it TAKES and ACCEPTS any kind of contribution, right @Melvin-Abraham? This is also ACCEPTED. If you take the Chromium Gerrit, millions f developers all over the world help in that. And the Gerrit accepts contributions. Same here. This section is really needed, but add this line:

```markdown
Minimum requirements for installing GAUDC: Node JS v12+
```
It works above v12 because I use v12.

**Comment by sumeshir26** [comment]
@im-coder-lg It does work on gitpod. check my PR

**Comment by im-coder-lg** [comment]
It's on your PR, but when I tested the shell script I made for GAUDC, it failed at the install script. You use noVNC, which is an excellent emulator, but I used the native Gitpod.

**Comment by im-coder-lg** [comment]
If anyone has the horsepower to run VMs, can that person test if GAUDC works on Debian, Ubuntu, and Fedora? Use node 16 and get it from that PPA or some repository (maybe but surely from cURL) which delivers the latest version.

**Comment by im-coder-lg** [comment]
> @im-coder-lg It does work on gitpod. check my PR

Moreover, checked the PR, and it's just cool, now that you can test GAUDC in a secure, risk-free environment.

**Comment by QuestYouCraft** [comment]
> What was that?

I will say it another way, literally: the first word is more expensive than the second. Initially, this saying is from the Russian language: "первое слово дороже второго". (translation into Hindi: "पहला शब्द दूसरे की तुलना में अधिक महंगा है".) @im-coder-lg, so you understand me?

I'll tell you the rest, test and check it out when I have free time. I'll be back in this pull request soon & I create the last pull request (which I will update from my fork) until @Melvin-Abraham merge pull request.

**Comment by im-coder-lg** [comment]
If you have enough horsepower, try using Ubuntu, Debian and Fedora. Mainly, use the latest Node JS LTS.

**Comment by Melvin-Abraham** [comment]
> No, but @im-coder-lg testing GAUDC. I can say for sure that this works on Windows 7+. I don't have time to test it on all OS yet. As soon as there is time, I will do it.

@QuestYouCraft You can take all the time you want. There's no pressure :)

**PS:** You need not close the Pull Request. Just make the changes and it will be automatically reflected here (just make sure the PR is open).

**Pull request closed without merging**
