### PR TITLE
feat: Gitpod Support

### PR DESCRIPTION
**Pull request by sumeshir26**
Make it easy for beginners to get started with contributing without installing Visual Studio, Node, and Windows Build Tools.

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Instead of changing the initial configuration, we can instead try to figure if the application is running in a Gitpod environment (possibly via `process.env`). If it is running in Gitpod, then in that case we can set the value for the required config keys in `assistantConfig` right after we load the saved configuration.

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Also, as of now I don't think this would be usable as the user can't upload their credentials or open the browser for authentication or have speaker input/output. Can you get that working somehow?

**Comment by sumeshir26** [comment]
@Melvin-Abraham The Audio does not work, but if you upload the credentials to the Gitpod workspace, I will show up in the app. But the 'Get Tokens!' screen would not work because I cannot open a new browser window. A fix for that can be made if we display the link which is supposed to open in the app.
Attached is a video clip of the credentials working in Gitpod.
[GAGitpod.zip](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/files/6501740/GAGitpod.zip)

**Comment by sumeshir26** [comment]
Getting the link can be done by something like[ the PR you made](https://github.com/endoplasmic/google-assistant/pull/94) for the `google-assistant` library and displaying a 'Copy Link' suggestion or display it on-scren.

**Comment by Melvin-Abraham** [comment]
I'll make some changes to the documentation before merging :)

**Comment by Melvin-Abraham** [comment]
> Getting the link can be done by something like[ the PR you made](https://github.com/endoplasmic/google-assistant/pull/94) for the `google-assistant` library and displaying a 'Copy Link' suggestion or display it on-screen. The PR can be pushed to your forked version of the library GAUDC now uses.

@sumeshir26 Even though copying the auth link is implemented, the link isn't actually copied to the clipboard. Can you check if the whole workflow works for you?

**Comment by sumeshir26** [comment]
@Melvin-Abraham Sure

**Comment by sumeshir26** [comment]
@Melvin-Abraham For me, the link is not copied as well. In the noVNC repo, it says that copy-paste is implemented. Doing some digging to find out how...

**Comment by sumeshir26** [comment]
@Melvin-Abraham I actually found a solution for this. You can put the link on the main window so it can be copied. See attachment.

**Comment by sumeshir26** [comment]
@Melvin-Abraham I need some help putting the link in the `innerHtml` of the `noAuthGrid` I looked on the web and tried to find the solution. I usually code in Python so this is kind of new to me. Thanks in advance!

**Comment by Melvin-Abraham** [comment]
> @Melvin-Abraham I need some help putting the link in the `innerHtml` of the `noAuthGrid` I looked on the web and tried to find the solution. I usually code in Python so this is kind of new to me. Thanks in advance!

No issues. I will add that in... 👍

**Comment by obed9057** [comment]
Wait isn’t javascript supposed to be easy-to-use I thought python was the hard one nvm Sent from Mail for Windows 10 From: Melvin. L. AbrahamSent: May 27, 2021 4:23 AMTo: Melvin-Abraham/Google-Assistant-Unofficial-Desktop-ClientCc: SubscribedSubject: Re: [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client] Gitpod Support (#389) @Melvin-Abraham I need some help putting the link in the innerHtml of the noAuthGrid I looked on the web and tried to find the solution. I usually code in Python so this is kind of new to me. Thanks in advance!No issues. I will add that in... 👍—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Turns out copying the auth link to clipboard works as expected. The thing is the logic for "Copy Auth Link" and "Retry" were swapped due to which it seemed like copy didn't work. You can try it out by clicking on "Retry" instead.

I will push the commit for that soon. Meanwhile, the commit 2ff582d in this PR could be reverted.

**Comment by sumeshir26** [comment]
@Melvin-Abraham Just reverted that...

**Comment by sumeshir26** [comment]
@Melvin-Abraham This works perfectly now! And once noVNC gets [this](https://github.com/novnc/noVNC/pull/1347) merged, the clipboard does not need to be used anymore.

**Comment by Melvin-Abraham** [comment]
I am halfway on the documentation part for Gitpod and will merge after its completion which will probably be after the next release

**Comment by im-coder-lg** [comment]
@sumeshir26 I am using the Dockerfile code in another project since I don't know much on Linux packages. I noticed that the building takes a lot of time, so if you add this code to the .gitpod.yml file, it will generate prebuilds so that you can get started easily. I suggest adding this so that it may help people get started faster.
Code:
```yaml
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
```

**Comment by im-coder-lg** [comment]
Update: I don't think the Gitpod Prebuild/Review in Gitpod comments work on PRs, looks like Gitpod won't allow that unless it is allowed by them.

**Comment by sumeshir26** [comment]
Closing due to inactivity

**Pull request closed without merging**
