### PR TITLE
Next

### PR DESCRIPTION
**Pull request by dorp007**
### Description
 Hi dedes can we users have a doker file for this, please?

### Resolved / Related Issues
- Closes #I_messed_up_my_contaner
- Addresses #IDK_how _to make_one

### Type of Change

- [x] Feature
- [x] Bug Fix
- [x] Documentation
- [x] H/A

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Do you know which branch you have added here? Moreover, GAUDC doesn't need Docker images. Already one of them is in a PR, ready to be merged soon(credits to @sumeshir26) but I can't understand what an actual Dockerfile will do here.

**Comment by im-coder-lg** [comment]
@Melvin-Abraham we can close this, @dorp007 added the `next` branch which is in WIP right now.

**Comment by Melvin-Abraham** [comment]
You seem to have created a PR mistakenly. You may want to start a [new discussion](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/discussions/new) or create a [new issue](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/new/choose) instead...

**Comment by Melvin-Abraham** [comment]
_Closing as invalid_

**Pull request closed without merging**
