### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by sumeshir26**
[Minor-Change README]

### CODE REVIEW

**Comment by coder-lg** [comment]
A small suggestion: add a fixes line, a checklist of some sorts that show what change it is and another checklist to check if there is errors, comments at hard-to-understand areas and if this is already an issue.
This is only a suggestion as I also use a PR template.

**Comment by sumeshir26** [comment]
@coder-lg I will add those

**Comment by coder-lg** [comment]
> @coder-lg I will add those

Thanks for considering :)

**Review by charlieporth1 — APPROVED** [review]

**Review by coder-lg — COMMENTED** [review]
Great change, try adding a # next to Fixes so that the person may put the issue number and link it :)

**Comment by Melvin-Abraham** [comment]
Thanks @sumeshir26 and @coder-lg for the contribution 👍
_Merging this PR_

**Comment by im-coder-lg** [comment]
Yup, this is good!

**Pull request merged**
