### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by QuestYouCraft**
See #480 for more info

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Wait, what is your OS? I know it would work on latest Linux distributions, but unsure about Mac OS

**Comment by QuestYouCraft** [comment]
Well, @im-coder-lg, I changed the pull request. Check #491.

**Comment by im-coder-lg** [comment]
You could have changed it here. Oh well, it's fine tho...

**Comment by QuestYouCraft** [comment]
> You could have changed it here.

How to?
*Okay, I'll figure it out later...*

**Comment by im-coder-lg** [comment]
> > You could have changed it here.
> 
> How to?
> _Okay, I'll figure it out later..._
> 

you should have done it in your fork

**Pull request closed without merging**
